# Generated by Django 5.0.8 on 2024-09-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_date_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
